// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Welcome
    {
        [JsonProperty("LogicalAddress")]
        public string LogicalAddress { get; set; }

        [JsonProperty("PortConfig")]
        public PortConfig PortConfig { get; set; }

        [JsonProperty("dataCenter")]
        public DataCenter DataCenter { get; set; }
    }

    public partial class DataCenter
    {
        [JsonProperty("appName")]
        public string AppName { get; set; }

        [JsonProperty("portName")]
        public string PortName { get; set; }

        [JsonProperty("meterModeName")]
        public string MeterModeName { get; set; }

        [JsonProperty("mqttUrl")]
        public string MqttUrl { get; set; }
    }

    public partial class PortConfig
    {
        [JsonProperty("PortList")]
        public PortList[] PortList { get; set; }

        [JsonProperty("PortTypeSelection")]
        public long PortTypeSelection { get; set; }
    }

    public partial class PortList
    {
        [JsonProperty("PortDescription")]
        public string PortDescription { get; set; }

        [JsonProperty("PortParameter")]
        public PortParameter PortParameter { get; set; }

        [JsonProperty("PortType")]
        public long PortType { get; set; }
    }

    public partial class PortParameter
    {
        [JsonProperty("BaudRate", NullValueHandling = NullValueHandling.Ignore)]
        public long? BaudRate { get; set; }

        [JsonProperty("DataBits", NullValueHandling = NullValueHandling.Ignore)]
        public long? DataBits { get; set; }

        [JsonProperty("Parity", NullValueHandling = NullValueHandling.Ignore)]
        public string Parity { get; set; }

        [JsonProperty("PortName", NullValueHandling = NullValueHandling.Ignore)]
        public string PortName { get; set; }

        [JsonProperty("StopBits", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? StopBits { get; set; }

        [JsonProperty("ServerIP", NullValueHandling = NullValueHandling.Ignore)]
        public string ServerIp { get; set; }

        [JsonProperty("ServerPort", NullValueHandling = NullValueHandling.Ignore)]
        public long? ServerPort { get; set; }
    }

    public partial class Welcome
    {
        public static Welcome FromJson(string json) => JsonConvert.DeserializeObject<Welcome>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Welcome self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
